@startuml quizr


class Tag << (S,#cccccc) Struct >>
class Tag {
    - name : string
}

class Ratio << (S,#cccccc) Struct >>
class Ratio {
    - antecedent : int
    - consequent : int
    + ToString() : string
    + {static} Normalize(r:Ratio) : Ratio
    + setAntecedent (a:int) : void
    + setConsequent (c:int) : void
    + getConsequent () : int
    + getAntecedent () : int
}

Measurable *-- Ratio
interface Measurable {
    + {abstract} getResult() : Result
    + {abstract} getDifficulty() : Difficulty
    + {abstract} getAttempts() : int
    + {abstract} setAttempts() : int
    + {abstract} getSuccessRate() : Ratio
    + {abstract} setSuccessRate() : Ratio
}

Measurable "1" *-- "1" Difficulty : contains
enum Difficulty {
    EASY
    MODERATE
    HARD
}

Measurable "1" *-- "1" Result : contains
enum Result {
    FAILED
    PASSED
    UNATTEMPTED
}

Catagorizable "1" *-- "1" TestType : contains
Catagorizable "many" *-- "many" Tag :  contains
interface Catagorizable {
    + {abstract} getType() : TestType
    + {abstract} getTags() : Tag
}

Question <|.. Measurable
abstract Question <T> {
    + {abstract} setQuestion() : void
    + {abstract} getQuestion() : string
    + {abstract} getAnswer() : T
    + {abstract} setAnswer (value:T) : void
    + {abstract} checkAnswer (T attempt) : void
}


enum TestType {
    MULTIPLE_CHOICE
    SHORT_ANSWER
    TRUE_FALSE
}
Question       <|..Catagorizable
MultipleChoice <|--Question
ShortAnswer    <|--Question
TrueFalse      <|--Question

class ShortAnswer {

}
class TrueFalse {

}

Test <|.. Catagorizable
Test <|.. Measurable
abstract Test {
    + {abstract} int Score()
}

class QuestionSet<T> {

}

QuestionSet "1" *-- "many" TrueFalse: contains
QuestionSet "1" *-- "many" ShortAnswer: contains
QuestionSet "1" *-- "many" MultipleChoice: contains
QuestionSet <|.. Test

Question *-- Answer
Answer <|.. Catagorizable
class Answer<T> {
    - value : T
    - type : TestType
    + {static} Evaluate (solution:Answer<string>, attempt:T) : boolean
    + {static} Evaluate (solution:Answer<bool>, attempt:T) : boolean
    + {static} Evaluate (solution:Answer<int>, attempt:T) : boolean
    + {static} Evaluate (solution:Answer<int[]>, attempt:T) : boolean
    --
    + getValue () : T
    + getType () : TestType
    + setType () : TestType
    + setValue (value:T) : void
}

@enduml